<?php
use Test\Data;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">导入场点</h3>
  </div>
  <div class="panel-body">
  
<?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<!-- 	<strong> Error </strong> The following errors have occurred:  -->
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>


  		<?php 
  		$form = $this->form;
  		$form->prepare();
  		echo $this->form()->openTag($form);
  		?>
<fieldset>
		  <br/>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">名称:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('name');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">文件:</label>
		    <div class="col-sm-10">
		    <input type="file" id="import_file" name="file">
		    </div>
		  </div>
		  
		  		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		  <?php echo $this->formElement($form->get('user_id')) ?>
		  <?php echo $this->formElement($form->get('project_id')) ?>
		  <?php echo $this->formElement($form->get('id')) ?>
		  <?php echo $this->formElement($form->get('submit')) ?>&nbsp;<?php echo $this->formElement($form->get('cancel')) ?>
		  </div>
		  </div>		   	
</fieldset>		
		<?php echo $this->form()->closeTag() ?>
</div>
</div>




<script>

 $('#import_file').on('change',function(){
		var filePath = $(this).val();
		var fileFormat = filePath.substring(filePath.lastIndexOf(".")).toLowerCase();
		// 检查是否是图片
		if(fileFormat != '.xls' && fileFormat != '.xlsx') {
			$('#name').val('');
			alert('上传错误,文件格式必须为：xls/xlsx');
		    return;  
		}
		$("#name").val(this.files[0].name);
		//src = window.URL.createObjectURL(this.files[0]); //转成可以在本地预览的格式
	});

	(function($){
		$(function(){
	 		$("[name='submit']").click(function(e){
	 			var name = $.trim($('#name').val());
	 			if(name == ''){
					alert('请上传文件');
					return false;
	 	 		}
	 			var importFile = $.trim($('#import_file').val());
	 			if(importFile == ''){
					alert('请上传文件');
					return false;
	 	 		}
	 			
	 		});
	 		if($("#id").val() > 0){
	 			$("[name='name']").attr("disabled",true);;
	 			$("[name='submit']").remove();
	 			$("[name='cancel']").remove();
	 			$("#import_file").replaceWith("<button id=\"exportExcel\">导出</button>");
		 	}
		 	$("#exportExcel").click(function(e){
			 	var name = $("[name='name']").val();
			 	window.location.href="/import/" + name;
		 		return false;
			});
		});
	})(jQuery);

</script>