<?php 
    $currentController = 'project';
    $listUrl = $this->url("default",array(
        "controller"=>$currentController,
        "action" => "list"
    ));
?>
<div class="panel panel-default">
      <div class="panel-body">
      
      <?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<!-- 	<strong> Error </strong> The following errors have occurred:  -->
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<!--  <li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>-->
	 		<li> <?php echo $v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>
      
        <form name="search" class="form-inline" role="form" action="<?=$listUrl;?>" method="get">
       
          <div class="form-group">
            <input value="<?php echo $this->param['name'];?>" type="text" name="name" class="form-control" id="name" placeholder="项目名称">
          </div>
          
          <button type="submit" class="btn btn-primary">搜索</button>
          </form>
          </div>

  <div class="panel-body">
	<table class="table table-striped">
			<tr>
				<th>项目名称</th>
				<th>创建时间</th>
				<th>操作</th>
			</tr> 
			 <?php foreach ($this->paginator as $row){ ?>
			<tr>
				<?php 
    				$editUrl = $this->url("default",array(
    				    "controller"=>$currentController,
    				    "action" => "index",
    				    "id" => $row['id']
    				));
				?>
			    <td> <?php echo $this->escapehtml($row['name']); ?></td>
			    <td> <?php echo $this->escapehtml($row['create_time']); ?> </td>
			    <td>
			    <?php 
			         $deleteUrl = $this->url("default",array(
			             "controller"=>$currentController,
                         "action" => "delete",
                         "id" => $row['id']
			         ));
    			    ?>			    
    			    <a class="checkDeleteUrl" href="<?php echo $deleteUrl;?>">删除</a>&nbsp;&nbsp;
			    </td>
			</tr>
			<?php } ?>
	</table>
	
	<?php
        
	 	// add at the end of the file after the table
	 	try {
			echo $this->paginationControl(
			    // the paginator object
			    $this->paginator,
			    'sliding',
			    // the partial to use to render the control
			    array('partial/paginator.phtml', 'Admin'),
			    // the route to link to when a user clicks a control link
			    array("route"=>'default','route_params'=>array('controller'=>$currentController,'action'=>'list'))
			);
		}catch (\Exception $e){
			echo $e->getMessage();
		}
	
	?>
</div>
</div>
