<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">编辑AP组</h3>
  </div>
  <div class="panel-body">
  
<?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<!-- 	<strong> Error </strong> The following errors have occurred:  -->
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<!--  <li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>-->
	 		<li> <?php echo $v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>


  		<?php 
  		$form = $this->form;
  		$form->prepare();
  		echo $this->form()->openTag($form);
  		?>
<fieldset>
		  <br/>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">AP组ID(必填,唯一):</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('ap_group_id');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">AP组名称(必填,唯一):</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('name');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">描述:</label>
			<div class="col-sm-10">
		    	<?php
		    	     $name = $form->get('description');
		    	     echo $this->formtextarea($name);
				?>
		    </div>
		  </div>
		  		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		  <?php echo $this->formElement($form->get('user_id')) ?>
		  <?php echo $this->formElement($form->get('project_id')) ?>
		  <?php echo $this->formElement($form->get('id')) ?>
		  <?php echo $this->formElement($form->get('submit')) ?>&nbsp;<?php echo $this->formElement($form->get('cancel')) ?>
		  </div>
		  </div>		   	
</fieldset>		
		<?php echo $this->form()->closeTag() ?>
</div>
</div>





 