<?php 
    $currentController = 'bas';
    $listUrl = $this->url("default",array(
        "controller"=>$currentController,
        "action" => "list"
    ));
?>
<div class="panel panel-default">
      <div class="panel-body">
        <form name="search" class="form-inline" role="form" action="<?=$listUrl?>" method="get">
       
          <div class="form-group">
            <input value="<?php echo $this->param['name'];?>" type="text" name="name" class="form-control" id="name" placeholder="bas名称">
          </div>
          
          <button type="submit" class="btn btn-primary">搜索</button>
          </form>
          </div>

  <div class="panel-body">
	<table class="table table-striped">
			<tr>
				<th>bas名称</th>
				<th>basID</th>
				<th>nas_ip</th>
				<th>创建时间</th>
				<th>修改时间</th>
<!-- 				<th>操作</th> -->
			</tr> 
			 <?php foreach ($this->paginator as $row){ ?>
			<tr>
				<?php 
    				$editUrl = $this->url("default",array(
    				    "controller"=>$currentController,
    				    "action" => "index",
    				    "id" => $row['id']
    				));
				?>
			    <td><a href="<?php echo $editUrl;?>"> <?php echo $this->escapehtml($row['name']); ?> </a> </td>
			    <td> <?php echo $this->escapehtml($row['bas_id']); ?> </td>
			    <td> <?php echo $this->escapehtml($row['nas_ip']); ?> </td>
			    <td> <?php echo $this->escapehtml($row['create_time']); ?> </td>
			    <td> <?php echo $this->escapehtml($row['update_time']); ?> </td>
			</tr>
			<?php } ?>
	</table>
	
	<?php
        
	 	// add at the end of the file after the table
	 	try {
			echo $this->paginationControl(
			    // the paginator object
			    $this->paginator,
			    'sliding',
			    // the partial to use to render the control
			    array('partial/paginator.phtml', 'Admin'),
			    // the route to link to when a user clicks a control link
			    array("route"=>'default','route_params'=>array('controller'=>$currentController,'action'=>'list'))
			);
		}catch (\Exception $e){
			echo $e->getMessage();
		}
	
	?>
</div>
</div>
